"""Initial migration.

Revision ID: dd493cd985d6
Revises: 
Create Date: 2023-01-05 17:33:54.306286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd493cd985d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('poster', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('poster')
        batch_op.drop_column('year')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
